import { Body } from "@/components/Core/Body";
import { ThemeContextProvider } from "@/styles/themeContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeContextProvider>
        <Body>{children}</Body>
      </ThemeContextProvider>
    </html>
  );
}
